import { Inter } from 'next/font/google'
// import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Oneeb Faisal | UI Designer',
  description: 'Generated by create next app',
  url: 'https://www.meoneeb.com',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta charSet="utf-8" />  
      <link rel="icon" href="/icons/fav.png" />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
